[build]
command = "flutter build web --release --dart-define=SUPABASE_URL=https://uoobzhkglbiwhwjrvljg.supabase.co --dart-define=SUPABASE_PUBLISHABLE_DEFAULT_KEY=sb_publishable_SFBM6cLLZ51aIrvpfDz4KQ_TlEEOQc0 --dart-define=CLOUDINARY_NAME=dmys15ako --dart-define=CLOUDINARY_PRESET=iblog_"
publish = "build/web"

[[plugins]]
package = "netlify-plugin-flutter"
[plugins.inputs]
channel = "stable"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
